# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
cache: packages
sudo: required
matrix:
  include:
    - os: linux
      dist: precise
      sudo: true
warnings_are_errors: false
apt_packages:
 - libfftw3-dev
r_binary_packages:
 - devtools
 - Rcpp
 
