# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('ramgcl_rcpp_hello_world', PACKAGE = 'ramgcl')
}

amgsolve <- function(ptr, col, val, rhs, guess, tol = 1e-5, maxiter = 100L, coarsening = "smoothed_aggregation", relax = "spai0", solver = "bicgstab") {
    .Call('ramgcl_amgsolve', PACKAGE = 'ramgcl', ptr, col, val, rhs, guess, tol, maxiter, coarsening, relax, solver)
}

amgsolve_ns <- function(ptr, col, val, rhs, guess, nS, tol = 1e-5, maxiter = 100L, coarsening = "smoothed_aggregation", relax = "spai0", solver = "bicgstab", max_levels = 4L, coarse_enough = 1L) {
    .Call('ramgcl_amgsolve_ns', PACKAGE = 'ramgcl', ptr, col, val, rhs, guess, nS, tol, maxiter, coarsening, relax, solver, max_levels, coarse_enough)
}

